name: Nuxt CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  pull-requests: write
  checks: write

jobs:
  checkVulnerability:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: run 'npm audit'
        run: npm audit --audit-level moderate

  setupAndValidate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: run 'npm install'
        run: npm install
      - name: run ESLint
        run: npm run lint
      - name: run build
        run: npm run build
      - name: run Test
        run: npm run test
      - name: Publish test results
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: reports/junit.xml
      - name: Publish test coverage
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage
          path: reports/coverage
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: reports/coverage/cobertura-coverage.xml
          fail_below_min: true
          thresholds: '1 75'
          format: markdown
          badge: true
          output: both
      - name: Add coverage to PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
