name: Nuxt CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: run 'npm ci'
        run: npm ci
      - name: run ESLint
        run: npm run lint
      - name: run Test
        run: npm run test
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: reports/coverage/cobertura-coverage.xml
          fail_below_min: true
          thresholds: '1 75'
          format: markdown